name: Wiki PDF

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Tectonic/
          key: ${{ runner.os }}-${{ env.cache-name }}-tectonic
      - name: Download pandoc+tectonic
        run: |
          wget -qO- https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.3.3/tectonic-0.3.3-x86_64-unknown-linux-gnu.tar.gz | tar xzvf - tectonic
          wget -qO- https://github.com/jgm/pandoc/releases/download/2.11.3.1/pandoc-2.11.3.1-linux-amd64.tar.gz | tar --strip-components=2 -xzvf - pandoc-2.11.3.1/bin/pandoc
          sudo mv -f pandoc tectonic /usr/local/bin
      - name: Build PDF
        run: |
          cat Home.md | sed '1,/<!--- TOC END -->/d' | cat .pandoc/meta.yaml - | pandoc --from=markdown --template=.pandoc/eisvogel.tex --toc --pdf-engine tectonic -o userguide.pdf
      - name: Upload PDF to release assets
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: userguide.pdf
          tag: userguide
          overwrite: true
